export const SET_LOADING = "SET_LOADING"
export const SET_ERROR = "SET_ERROR"
export const POST_AD = "POST_AD"
export const GET_AD = "GET_AD"
export const DELETE_AD = "DELETE_AD"
export const UPDATE_AD = "UPDATE_AD"